version: '3'
services:
  app: # to równocześnie nazwa hosta
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  cypress:
    image: cypress/included:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000 # użycie hostname serwi